bagelbids/merge.py, bagelbids/tests/test_merge.py
=> remove subjects not in demographics

bagelbids/cli.py, bagelbids/tests/test_cli.py, setup.cfg
=> Switching to typer

bagelbids/tests/data/example2.json, bagelbids/tests/data/example3.tsv, bagelbids/tests/data/example4.json, bagelbids/tests/data/example5.json, bagelbids/tests/data/example6.tsv, bagelbids/tests/data/example7.json
=> Change symlinks to regular file

.github/workflows/test.yml, .pre-commit-config.yaml, pyproject.toml, setup.cfg
Linter configs have also now been updated to match the API/PEP8 standards.
=> Set up pre-commit and code coverage

.pre-commit-config.yaml, bagelbids/cli.py, bagelbids/dictionary_models.py, bagelbids/mappings.py, bagelbids/models.py, bagelbids/tests/conftest.py, bagelbids/tests/test_cli_pheno.py
Goes along with https://github.com/neurobagel/bagelbids/pull/54:
- apply the rules to the codebase
- a minor version bump for isort
=> Apply code styling rules

bagelbids/cli.py, bagelbids/mappings.py, bagelbids/tests/data/example2.json, bagelbids/tests/data/example2.tsv, bagelbids/tests/test_cli_pheno.py, setup.cfg
=> Add age property

bagelbids/cli.py, bagelbids/models.py, bagelbids/tests/test_cli_pheno.py
Closes #63 
Also closes #66 which I discovered while working on this
=> Add context handler

bagelbids/tests/data/example_synthetic.json, bagelbids/tests/data/example_synthetic.jsonld, bagelbids/tests/data/example_synthetic.tsv, bagelbids/tests/test_cli_pheno.py
Closes #39 
@alyssadai: I have only done some rudimentary checks on the output file. I wouldn't use it to write tests against yet, or before you take a closer look.
=> add example for BIDS synthetic data

bagelbids/cli.py, bagelbids/mappings.py, bagelbids/tests/test_cli_bids.py
- test_cli_add_bids.py also renamed to test_cli_bids.py
Closes #29
Closes #79
=> Parse and add BIDS metadata to phenotypic dataset from jsonld

bagelbids/pheno_utils.py, bagelbids/tests/test_utility.py
=> Update transform_age utility

bagel/cli.py, bagel/models.py, bagel/tests/data/example_synthetic.jsonld, bagel/tests/test_cli_bids.py, bagel/tests/test_utility.py
=> Encode absolute file path

bagel/cli.py, bagel/tests/test_cli_bids.py
=> Add function and unit tests for getting session paths

bagel/cli.py, bagel/pheno_utils.py, bagel/tests/test_utility.py
The main changes are:
- Added an informative error for mismatched age values & heuristic
- Remove NaN handling by pd.read_csv to allow raw missing values to be parsed in phenotypic tsv
Closes #71, closes #85, closes #93
=> Bug fixes related to age value/transformation handling

bagel/cli.py
=> [FIX] Force phenotypic .tsv to be read a string

bagel/pheno_utils.py, bagel/tests/data/README.md, bagel/tests/data/example_synthetic.jsonld
=> Create `cogAtlas` namespace and update examples + example README

.github/workflows/cd.yml
this caused the cd workflow to systematically fail
see here
https://github.com/neurobagel/bagel-cli/actions/workflows/cd.yml
=> [FIX] fix typo cd.yml

bagel/dictionary_models.py, bagel/pheno_utils.py, bagel/tests/data/example1.json, bagel/tests/data/example10.json, bagel/tests/data/example11.json, bagel/tests/data/example12.json, bagel/tests/data/example13.json, bagel/tests/data/example14.json, bagel/tests/data/example15.json, bagel/tests/data/example2.json, bagel/tests/data/example4.json, bagel/tests/data/example5.json, bagel/tests/data/example6.json, bagel/tests/data/example7.json, bagel/tests/data/example8.json, bagel/tests/data/example9.json, bagel/tests/data/example_invalid.json, bagel/tests/data/example_synthetic.json, bagel/tests/test_utility.py
Closes #151 
Closes #159 
- `Transformation` field for continuous columns made mandatory
- New classes of accepted Neurobagel column annotations added to data dictionary model: `IdentifierNeurobagel`, `ToolNeurobagel`
- Each column class contains at least one required field unique to that class
- Examples updated
- Partially annotated column data dictionaries now fail data dictionaray schema validation
- `if` checks that run validations on the data dictionary only refactored into a separate function
For bug fixes:
=> [FIX] Updates to data dictionary model schema

.github/workflows/cff_validation.yml, CITATION.cff
Related to #147 
- added citation file
- added citation validation workflow
=> [INFRA] Add citation file and validation workflow

.github/workflows/test.yml
Closes #193 
- Updated the test workflow file to install dependencies as outlined in the [`README.md`](https://github.com/neurobagel/bagel-cli#setting-up-a-local-development-environment)
For bug fixes:
=> [CI] Updated test workflow

.github/dependabot.yml
Changing dependabot label to `_bot`
For bug fixes:
=> [REF] Change dependabot label

bagel/mappings.py, bagel/pheno_utils.py, bagel/tests/data/example1.json, bagel/tests/data/example10.json, bagel/tests/data/example11.json, bagel/tests/data/example12.json, bagel/tests/data/example13.json, bagel/tests/data/example14.json, bagel/tests/data/example15.json, bagel/tests/data/example2.json, bagel/tests/data/example4.json, bagel/tests/data/example5.json, bagel/tests/data/example6.json, bagel/tests/data/example7.json, bagel/tests/data/example8.json, bagel/tests/data/example9.json, bagel/tests/test_cli_pheno.py, bagel/tests/test_utility.py
Closes #139
- New prefix and URL defined for the term for healthy controls
- Example JSON files updated with new TermURL
- New test added that all prefixes used in our reference data dictionary have an entry in the `@context`
- employs a new helper function that gets all values for instances of a specific key in a dictionary
For bug fixes:
=> [FIX] Add NCIT namespace

bagel/bids_utils.py, bagel/cli.py, bagel/pheno_utils.py
=> [MNT] Update help text and fix formatting issues in user messages

bagel/pheno_utils.py, bagel/tests/data/example12.json, bagel/tests/data/example13.json, bagel/tests/data/example14.json, bagel/tests/data/example15.json, bagel/tests/data/example16.json, bagel/tests/data/example2.json, bagel/tests/test_utility.py
Closes #128 
- Capitalized age heuristics
- Update CLI logic and related tests
- Created issues in [annotation_tool](https://github.com/neurobagel/annotation_tool/issues/561), [documentation](https://github.com/neurobagel/documentation/issues/101), and [neurobagel_example](https://github.com/neurobagel/neurobagel_examples/issues/12) repos to update the heuristics accordingly
For bug fixes:
=> [MNT] Capitalized age heuristics

README.md
Related to https://github.com/neurobagel/planning/issues/41
-
-
For bug fixes:
=> [DOC] Added link to official docs

.github/workflows/build_docker_on_release.yml
=> [CI] Update image tag for default build + add wf to build on release

.autorc, .github/workflows/release.yaml
=> [CI] Added `release` workflow

.autorc, bagel/tests/conftest.py
=> [CI] Update .autorc to release with release label

bagel/tests/test_cli_pheno.py
- Closes #
- Test that phenotypic sessions get the right labels from the tsv file
For bug fixes:
=> [TST] Added a test to ensure correct labelling of phenotypic sessions

.github/workflows/test.yml
- Codecov set up for bagel-cli repo and code coverage uploading added to `test.yml`
For bug fixes:
=> [CI] Add Codecov to test workflow

.github/workflows/release.yaml
=> [CI] give auto-release permissions to launch build

.pre-commit-config.yaml
=> [MNT] Stop pre-commit from pushing to PR branches

.github/workflows/release.yaml
- Since a PR cannot be approved by the PR author (which currently prevents the CHANGELOG.md generated by `auto` from being merged into a protected branch, see https://github.com/neurobagel/bagel-cli/actions/runs/7450231608/job/20269242826) switch to using a different PAT for the protected branch reviewer (required by the `protected-branch` plugin) than the rest of the release process
For bug fixes:
=> [FIX] Use different reviewer token in release.yaml

bagel/cli.py, bagel/tests/data/README.md, bagel/tests/data/example21.json, bagel/tests/data/example21.tsv, bagel/tests/test_cli_pheno.py
- Closes #312
- when using [pd.DataFrame.query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html), column names are now quoted w/ backticks so that characters not valid in Python variables can be read
- prevents column names from being truncated during the query
- README table of example data also reformatted for readability/easier updating
For bug fixes:
=> [FIX] Handle dashes (/any chars that are not python variable valid) in column names

bagel/bids_utils.py, bagel/tests/test_utility.py
- Closes #230
- When BIDS dataset contains IDs not found in the phenotypic JSONLD, include in error message a reminder that subject IDs are treated as case sensitive by the CLI
For bug fixes:
=> [DOC] Note case sensitivity of subject IDs in `bids` IDs check error

.autorc, .github/workflows/release.yaml
- Adapted from suggestion in https://github.com/intuit/auto/issues/1491#issuecomment-1610120918
- Alternative to using `protected-branch` plugin, since the process of opening + auto-merging PRs in that plugin is causing conflicts with other CI checks (pre-commit CI)
For bug fixes:
=> [CI] Temporarily enable force pushes in release workflow

.autorc
=> [CI] Change release author to admin

.autorc, .github/workflows/release.yaml
=> [CI] Try classic PAT in release.yaml

.autorc, .github/workflows/release.yaml
=> [CI] Remove `protected-branch` plugin (again) now that we're using an app token

README.md
=> [DOC] Minor capitalization fix in README.md

.github/workflows/release.yaml
This release introduces short option names for CLI commands and fixes a bug that prevented hyphens in column names from being parsed.
=> [CI] Release the CLI

bagel/cli.py, bagel/derivatives_utils.py, bagel/tests/test_cli_bids.py, bagel/tests/test_utility.py, bagel/utility.py
- Closes #346 
- Both `bagel bids` and `bagel derivatives` can now handle input JSONLDs which have metadata from the other command, and add data to existing imaging sessions
- This includes existing Neurobagel-created sessions, when sessions are missing in the dataset
- `get_imaging_session_instances()` turned into a shared util
**NOTE: This PR will not have a PR label b/c it is being merged into another branch instead of `main`**
For bug fixes:
=> [ENH] Update `bagel bids` to handle JSONLD inputs incl. derivative metadata

bagel/logger.py, bagel/utilities/pheno_utils.py, tests/data/README.md, tests/data/example22.json, tests/data/example22.tsv, tests/integration/test_cli_pheno.py, tests/unit/test_pheno_utils.py
- Closes #507 
- Check for empty ID values first among checks
- Include tips about common reasons for errors
- Print row indices as part of error message where relevant
- Switch to 1-based indexing for problematic rows for easier user troubleshooting
For bug fixes:
=> [ENH] More user-friendly error messages for `pheno` command input validation

bagel/cli.py, bagel/utilities/bids_utils.py, tests/integration/test_bids2tsv.py, tests/unit/test_bids_utils.py
- Fixes #539 
- Only retain NIfTI rows with BIDS-supported suffixes in BIDS metadata table
- Warn when unsupported suffixes detected
For bug fixes:
=> [FIX] Filter `bids2table`-generated table by BIDS supported suffixes
