neurobagel/bagel-cli

bagelbids/dictionary_models.py
Added pydantic classes for a BIDS compatible data dictionary with additional annotations. 
Related to https://github.com/neurobagel/annotation_tool/issues/199
=> data dictionary schema

bagelbids/cli.py, bagelbids/tests/conftest.py, bagelbids/tests/data/README.md, bagelbids/tests/data/example_invalid.json, bagelbids/tests/test_cli.py, bagelbids/tests/test_pheno.py, setup.cfg
Closes #31 
Changes:
- added `test_pheno` to test the new subcommand
- `test_pheno` contains unit tests of methods inside of the `cli.py` module. `test_cli` has one (very basic) integration test that runs the actual CLI
- added additional test data
- 
Note: 
- Because we currently have only one subcommand (`pheno`), the CLI still behaves as if there was no subcommand. I.e. you can still call it with simply `bagel --pheno /my/pheno/file.tsv ...`). This will change as soon as we add a second subcommand
- This is all in one commit because I thought I was being clever with stacking my PRs...
=> validate data dictionary

bagelbids/cli.py, bagelbids/mappings.py, bagelbids/tests/data/README.md, bagelbids/tests/data/example8.json, bagelbids/tests/data/example8.tsv, bagelbids/tests/data/example_invalid.tsv, bagelbids/tests/test_cli_pheno.py
Closes #34 
New functionality:
- `get_columns_about` to grab column names that are annotated with a specific category / concept that we know about (here only `participant_id` is used)
- validation that only one participant and session ID column each are provided (because we cannot yet deal with more than one)
- subject-level parsing of a provided .tsv
- serialization of a neurobagel Dataset instance
Note: 
- we currently don't parse any information inside of the .tsv file because we don't yet know how to deal with things like "age", "sex", etc (that comes next)
- we currently completely ignore sessions (not even creating session instances in the graph or output). That's partly because we have nothing yet to say about sessions (other than that they exist) and partly because session …
=> pheno subcommand can serialize a graph instance

bagelbids/cli.py, bagelbids/mappings.py, bagelbids/tests/data/example1.json, bagelbids/tests/data/example2.json, bagelbids/tests/data/example2.tsv, bagelbids/tests/data/example4.json, bagelbids/tests/data/example5.json, bagelbids/tests/data/example6.json, bagelbids/tests/data/example7.json, bagelbids/tests/data/example8.json, bagelbids/tests/test_cli_pheno.py
Closes #41 
Implements parser for the `sex` attribute. Because `"sex"` (and all other phenotypic attributes) are still attached to the subject, if there are multiple rows per subject in the `pheno.tsv` file, we only process the first one.
Also: me figuring our type hinting on python 3.9. At least we now have a good reason for testing multiple versions!
=> Add sex attribute

bagelbids/cli.py, bagelbids/mappings.py, bagelbids/models.py, bagelbids/tests/data/example6.tsv, bagelbids/tests/test_cli_pheno.py
Closes #42 
This PR enables the CLI to add "diagnosis" information from the phenotypic .tsv to the output file.
=> Implement handling of diagnosis attributes

bagelbids/cli.py, bagelbids/mappings.py, bagelbids/models.py, bagelbids/tests/data/README.md, bagelbids/tests/data/example6.json, bagelbids/tests/data/example6.tsv, bagelbids/tests/test_cli_pheno.py
Closes #28 
- Adds new function to create a tool -> column map so we can know what columns have been labeled as `IsPartOf` the same tool.
- Adds a function to assert that for a row in the pheno.tsv and a list of columns, all values are not missing. Our current rule for stating that an assessment tool "is available" for a subject is that none of the columns labeled as "IsPartOf" the respective tool have missing values. This might change at some point.
=> Adding assessment tool attribute

bagelbids/cli.py, bagelbids/tests/conftest.py, bagelbids/tests/test_cli_pheno.py, bagelbids/tests/test_utility.py
For simplicity, the tests not depending on the CLI runner have been moved to their own test suite first, before any refactoring in  `cli.py`. The PR for issue #59 will address the refactoring of the associated `cli.py` functions into a `utility.py` module.
2 new tests have been added:
- `test_invalid_age_heuristic`
- `test_generate_context`
Closes #52
=> Refactor pheno tests

.pre-commit-config.yaml, bagelbids/cli.py, bagelbids/tests/test_cli_bids.py
- Added a `create_session` utility function + test
Closes #82
=> Implement handling of subjects with BIDS data but no session layers

bagel/bids_utils.py, bagel/cli.py, bagel/models.py, bagel/tests/data/example_synthetic.jsonld, bagel/tests/test_cli_pheno.py, bagel/tests/test_utility.py
Closes #110 
As part of this PR, the `example_synthetic.jsonld` test target had to be re-generated because the data model has changed, and the old  target file therefore wouldn't pass validation. I did a quick visual check, but would be good to check this again - after all it's a bit circular.
=> [FIX] ensure controlled terms have identifiers

bagel/cli.py, bagel/mappings.py, bagel/models.py, bagel/pheno_utils.py, bagel/tests/data/example1.json, bagel/tests/data/example10.json, bagel/tests/data/example11.json, bagel/tests/data/example2.json, bagel/tests/data/example4.json, bagel/tests/data/example5.json, bagel/tests/data/example6.json, bagel/tests/data/example7.json, bagel/tests/data/example8.json, bagel/tests/data/example9.json, bagel/tests/data/example_synthetic.json, bagel/tests/data/example_synthetic.jsonld, bagel/tests/test_cli_bids.py, bagel/tests/test_cli_pheno.py, bagel/tests/test_utility.py
- Controlled terms and model class attributes (properties) have been renamed according to https://github.com/neurobagel/encarta/blob/main/docs/standards.md. Tests and example files have also been updated.
- Used namespaces are now stored in `namedtuples` and prefixes accessed through the corresponding field
- New constant created to store labels and URIs of age heuristics
Closes #124, closes #89, closes #125
=> Align terms to naming standards, refactor use of namespaces

bagel/bids_utils.py, bagel/cli.py, bagel/models.py, bagel/pheno_utils.py, bagel/tests/data/example_synthetic.jsonld, bagel/tests/test_cli_pheno.py, bagel/tests/test_utility.py
Closes #129, closes #138.
- Separate classes reimplemented for controlled terms, except they inherit from a common class (`ControlledTerm`)
- New test added which checks that in a CLI-outputted .jsonld, classes provided as `schemaKey` values for an attribute also have a definition in the `@context` (will help catch future occurrences of classes not defined explicitly in `models.py` appearing in the .jsonld as a namespace-less element)
- `nb:range` age heuristic removed
For bug fixes:
- N/A, bug fixed in this PR was not caught by original set of tests
=> [FIX] Reimplement controlled term classes

bagel/cli.py, bagel/pheno_utils.py, bagel/tests/data/README.md, bagel/tests/data/example_synthetic.json, bagel/tests/data/example_synthetic.jsonld, bagel/tests/data/example_synthetic.tsv, bagel/tests/data/example_synthetic_pheno-bids.jsonld, bagel/tests/test_cli_pheno.py
Closes #144
- Missing value annotations + entries added for `Age`, `Sex`, and `Diagnosis` in the `example_synthetic` data files
- `pheno` command updated to only create + assign instances of Sex when values aren't missing 
- Added a sample "final" .jsonld file containing both pheno + BIDS metadata for `example_synthetic`
- Updated test data README with descriptions of available .jsonld examples
=> [ENH] Add all possible cases of missing values to `example_synthetic`

bagel/pheno_utils.py, bagel/tests/test_utility.py
Closes #153 
See also #151 and #152
- consider a column to be `categorical` inside the CLI **only** if there is a `"Levels"` key in the `"Annotations"` portion of the data dictionary
For bug fixes:
=> [FIX] Detect categorical column based on annotations

bagel/bids_utils.py
=> [FIX] Resolve session path for subjects with single session

bagel/cli.py, bagel/tests/test_cli_bids.py, bagel/tests/test_cli_pheno.py, bagel/utility.py
Closes #157
- `--output` argument changed to specify a file path instead of a directory, and is no longer required for either command (defaults if unset are `pheno.jsonld`/`pheno_bids.jsonld`)
- `--overwrite` flag added which will overwrite an existing output file if set
- if unset and the output file exists, program exits with informative message 
- new fixtures created for default output file path to use in tests
For bug fixes:
=> [ENH] Provide overwritable output file path instead of directory path arg

bagel/bids_utils.py, bagel/cli.py, bagel/tests/test_utility.py
Closes #190 
- Check for BIDS subject IDs missing from the phenotypic JSONLD _before_ slow `BIDSLayout` initialization
- This is done by simply extracting BIDS subdirectory names (see #190 issue description for why pybids functions are limited here)
- Print more intermediate messages during `bagel bids` command to indicate program progress
For bug fixes:
=> [REF] Refactor phenotypic/BIDS subjects check and add more intermediate stdout for `bagel bids`

bagel/cli.py, bagel/pheno_utils.py, bagel/tests/test_cli_pheno.py, bagel/tests/test_utility.py
Closes #175
- CLI will now process a subject as "having" a given assessment if they have a non-missing value for _any_ of the columns (items) belonging to that assessment
For bug fixes:
=> [ENH] Change assessment tool availability heuristic to `any()`

bagel/cli.py, bagel/models.py, bagel/pheno_utils.py, bagel/tests/data/README.md, bagel/tests/data/example17.json, bagel/tests/data/example17.tsv, bagel/tests/test_cli_bids.py, bagel/tests/test_cli_pheno.py
- Created subclasses of the "Session" class -> `PhenotypicSession` and `ImagingSession`
- Updated logic for `bagel pheno` command to populate attributes for every session that exists in the input phenotypic TSV
- Updated the existing tests to check at the appropriate level of depth in the output JSONLD files for variables
- Regenerated the reference example_synthetic JSON and JSONLD following the new session-level phenotypic model
- Updated the `bagel bids` command tests to look at only imaging sessions in the output
- Added example17 which includes no phenotypic sessions (`session_id` column) in the phenotypic TSV (but this is currently not tested by any tests)
For bug fixes:
=> [MODEL] Update data model to include longitudinal pheno data when sessions exist in TSV

.autorc, .github/workflows/release.yaml
- Closes #259 
Here's my attempt at using the `protected-branch` plugin, based on [these](https://github.com/intuit/auto/tree/main/plugins/protected-branch#protected-branch-plugin) docs 🤷
I also added the [`first-time-contributor`](https://github.com/intuit/auto/tree/main/plugins/first-time-contributor) plugin since I was updating the list anyways 🙈 
For bug fixes:
=> [CI] Allow auto to push on protected branch

.pre-commit-config.yaml, setup.cfg
It seems to lead to false positive results when
run in the pre-commit CI
- Related to https://github.com/neurobagel/documentation/issues/191
- disable flake8 E203 locally
- disable flake8 E203 for pre-commit specifically (since it apparently doesn't use the project config)
For bug fixes:
=> [MNT] Ignore flake8 rule E203

.autorc
- Auto-release wf is currently [failing](https://github.com/neurobagel/bagel-cli/actions/runs/10002197859/job/27673133238) because the required status check option for `protected-branch` apparently relies on PAT having the "Checks" permission, which is (amazingly) currently [not supported](https://github.com/orgs/community/discussions/129512) even though it is [documented](https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-checks?apiVersion=2022-11-28#about-check-runs)
- As a workaround, we will try to remove the status check option from the `auto` config, and apply it in the repo setting instead to trigger the check
For bug fixes:
=> [CI] Remove required status check from .autorc

.github/workflows/release.yaml
- Closes #
- `Neurobagel Chef Bot` (app created under neurobagel org) has been installed for bagel-cli
- Private key added as an organization-level actions secret
- App ID added as a repo-level actions variable
- Allowed to bypass branch protection rules in bagel-cli repo settings
For bug fixes:
=> [CI] Use `neurobagel-chef-bot` app access token in release.yaml

bagel/pheno_utils.py, bagel/tests/data/README.md, bagel/tests/data/example_invalid_json.json, bagel/tests/data/example_iso88591.json, bagel/tests/data/example_iso88591.tsv, bagel/tests/test_utility.py, bagel/utility.py
- Closes #314 
- Closes #167 
- Explicitly require UTF-8 encoding of inputs for the `bagel pheno` command
- Print informative error message (without a traceback!) when a UnicodeDecodeError or JSONDecodeError are encountered
- Return more details about offending entry in data dict when jsonschema validation fails
**For reviewer: Any thoughts on whether this should have the `pr-patch` or `pr-bug-fix` label?**
For bug fixes:
=> [ENH] More user-friendly handling of input decoding/reading errors

bagel/models.py
- Closes #343 
- Add info about availability of a completed pipeline run, pipeline name, and pipeline version to the imaging session model
- `hasAcquisition` turned into optional property, to account for imaging sessions that only have pipeline/derivative data attached
For bug fixes:
=> [MODEL] Model basic pipeline availability info in imaging session

README.md
- Instructions for setting up code linting moved from [docs](https://neurobagel.org/cli/#setting-up-code-formatting-and-linting-recommended) to README, since it pertains to the dev environment
- README will be inherited by the docs page as part of https://github.com/neurobagel/documentation/issues/230
For bug fixes:
=> [DOC] Move pre-commit setup to README.md

README.md
- Closes #https://github.com/neurobagel/planning/issues/200
-
-
For bug fixes:
=> [ENH] Add consistent badges
